name: UltimaGames

version: 0.7

description: All Ultima games.

authors: [Thalrod, Liven]

api-version: 1.14

main: fr.groupeultima.org.UltimaGames

commands:
  play:
    description:
  ultimagames:
    description: Main plugin command.
    permission: op